### ISSUE TITLE
Smaller dataset

### ISSUE THREAD

**Issue by aamay** [IBM/AMLSim#24]
I tried to generate one for 100 nodes but got problems with the in-degree and out-degree, even though they seemed equal in the param file I tinkered with. I didn't find the wiki pages very helpful on this.
Could you provide a param file for a really small dataset, e.g. 30 nodes, to be used for visualisation purposes?

**Comment by badicst** [comment]
It is not enough that the sum of in-degree equals the sum of out degree. The inner product of in-degree with the count must also be equal to the inner product of out-degree with the count. Because this expression gives the number of edges, it should be consistent computed from in- and out-degrees. You can use e.g. 
1,2,2
2,1,1
and in the parameter file accounts.csv set the number of accouts (the count field) to be 30. Then, the node degree will be reused the number of times needed.
Tamás

**Comment by aamay** [comment]
Thanks Tamás, I wonder if this can be done programmatically?
Also found another param file for a small dataset.

**Comment by badicst** [comment]
Do you mean how to generate a large consistent degree distribution? I don't know how they do, but the problem remains: how you want to control the degree distribution. It is your choice. And the answer (the algorithm that consistently creates the exact in- and out-degree distribution) depends on that.

**Comment by aamay** [comment]
Yup exactly, when I was running my experiments I specified the in-degrees and had so much trouble finding a consistent set of out-degrees.
